### ISSUE TITLE
Community and discussion

### ISSUE THREAD

**Issue by harikt** [somos/framework#30]
* IRC or Slack ?
* Google groups for discussion

**Comment by mvriel** [comment]
Good question; I didn't expect people to see the project this early on as I started it as an experiment and made it public with the idea of using Github issues to document what needs to be done and for people to provide input.

I have created a Google Groups (https://groups.google.com/forum/#!forum/somos-framework) for general questions and discussions; I think I'll keep the rest on Github for now.
